name: Upload Website

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1
    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.S3_ACCESS_ARN }}
        role-session-name: websitedeploy
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./public/ s3://arn:aws:s3:::bpirrocco.dev --delete
